// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aknpqhchwgwiuujfpzho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbnBxaGNod2d3aXV1amZwemhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Njg1MTYsImV4cCI6MjA3MDU0NDUxNn0.0NetDlgtkY6q29RTFRB0geaZBcGYUusiNU-A9rYvM5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});